### ISSUE TITLE
Install task fails if test:prepare task does not exist

### ISSUE THREAD

**Issue by DavidColby** [rails/jsbundling-rails#10]
If a Rails app does not have `test:prepare` defined, the install task fails with:

```
rails aborted!
Don't know how to build task 'test:prepare' (See the list of available tasks with `rails --tasks`)
Did you mean?  db:test:prepare
```

The most common path to get into this state is likely generating a new Rails app with `-T` to skip the default test framework (perhaps in favor of rspec or another alternative)

```
rails new no_tests -T
cd no_tests 
bundle add jsbundling-rails
rails javascript:install:esbuild #errors out
```

The same issue exists on cssbundling-rails

A simple fix is something like:

```ruby
# lib/tasks/jsbundling/build.rake
Rake::Task["test:prepare"].enhance(["javascript:build"]) if Rake::Task.task_defined?("test:prepare")
```

Happy to open a PR to resolve this error and on cssbundling-rails, if this is something that you would like to address.

**Comment by dhh** [comment]
Please do 👍
