### ISSUE TITLE
db:tests:prepare enchanced with javascript:build

### ISSUE THREAD

**Issue by JelF** [rails/jsbundling-rails#102]
It is not designed to do so. Right now i cannot use `ActiveRecord::Migration.maintain_test_schema!`  because it calls yarn.

I understand importance of backwards compatibility, but there at least should be some flag. Best of all if it would rely on `config.assets.compile`

**Comment by jthornhill** [comment]
I can reproduce this behavior when running system tests.

The use case here is to run system tests using an already-built docker image that includes the assets:precompile step. In Rails 6 / webpacker days this worked fine. I like to do it this way so we can verify that the assets are already built correctly before deploying.

I had assumed that config.assets.compile would be respected but it doesn't seem to be. Is there an alternate way to disable firing recompilation during tests?

**Comment by dhh** [comment]
Would take a patch for `SKIP_YARN_BUILD` that makes `javascript:build` a no-op.

**Comment by dhh** [comment]
`SKIP_YARN_BUILD` has been added.
