### ISSUE TITLE
yarn build --watch to scream a fail into the browser

### ISSUE THREAD

**Issue by maxence33** [rails/jsbundling-rails#104]
Hello, 
One nice feature to have would be jsbundling-rails to return an error in the browser in case of a `yarn build` failing, either the Rails way, or by a simple alert. (so we can check Puma or retry a `yarn build` to get proper message) 
and kudos for the gem. It's really good.

**Comment by dhh** [comment]
If you're using `bin/dev`, you'll get all the errors in the console. I don't see a straight path to have this happen in the browser. Part of this new setup is to ensure that Rails doesn't have to know about the specific compile step.
