### ISSUE TITLE
Detect the use of Yarn PnP when using esbuild

### ISSUE THREAD

**Issue by TakaiSaisei** [rails/jsbundling-rails#112]
It seems that jsbundling-rails knows absolutely nothing about Yarn versions above 1.x. If Yarn version globally set to 2.x or 3.x, and `rails new myapp -j esbuild` is called - JS bundling does not work unless you fix it yourself. Yarn Modern uses Plug'n'Play as default installing option and it breaks Rails environment.

For reference: Yarn Plug'n'Play drops old idea of having `node_modules` dir in app folder - instead it caches all dependencies and generates `.pnp.cjs` file that maps them to `package.json` entries. Without ESBuild plugin `esbuild-plugin-pnp` it will not work, as ESBuild will try to find dependencies in `node_modules` folder.

As I think we should look for Yarn version and/or Yarn `nodeLinker` config - if Yarn version is higher than 1.x, `nodeLinker` is not explicitly set to `pnpm` or `node_modules`, choose one of the strategies:

- Add `esbuild-plugin-pnp`, use ESBuild API and enable this plugin.
- Create a `.yarnrc` and set linker to `pnpm` or `node_modules`.
- Change the Yarn version for this project to 1.x.

**Comment by dhh** [comment]
We should enforce use of Yarn 1.x. Feel free to investigate.
