### ISSUE TITLE
Files must be named `application.js` to be taken into account by sprockets

### ISSUE THREAD

**Issue by juligarji** [rails/jsbundling-rails#115]
the files must be named `application.js` so that sprockets takes them into account and copies them to the public assets folder used by the application.

If I put as entrypoint a file with another name, it is generated in the `assets/builds` folder without problems but it is not taken into account by sprockets, so if I try to reference that using a `javascript_include_tag` doesn't exist

I have these versions of gems in my project:
gem 'sprockets', '3.7.2'
gem 'jsbundling-rails', '1.0.2'
'esbuild': '^0.14.39',

How can I configure my project to use another file names ?

**Comment by jotolo** [comment]
Hi @juligarji ! Did you add the name of your file to the sprocket manifest file? You need to tell Sprockets to consume this file.
