### ISSUE TITLE
Avoid running yarn install on javascript:build

### ISSUE THREAD

**Issue by IsmailM** [rails/jsbundling-rails#118]
https://github.com/rails/jsbundling-rails/blob/90833fba708fb415447492fad6d6d2b6961ee5aa/lib/tasks/jsbundling/build.rake#L1-L4

At the moment, `rake javascript:build` runs `yarn install && yarn build`. In my opinion, `yarn install` should not be part of the javascript building step at all. If it needs to be there, there should at least be an option to disable this (e.g. by having a separate task for `yarn install` - which can be overwritten or via a ENV variable etc.).

`css-bundling` does the same thing - so if you are using both `css-bundling` and `js-bundling` gems, assets-precompile will run `yarn install` twice.

Not only does this take slightly longer, it means post-install scripts are run multiple times...

Also, see https://github.com/rails/webpacker/issues/405.

**Comment by gsouf** [comment]
@IsmailM I believe like you that install should not be part of it. But it's sadly not the philosophy of this package https://github.com/rails/jsbundling-rails/issues/107#issuecomment-1082897448

You can just overwrite the build task, they said. That to me is equivalent to not using this gem as apart from the task it does not do much

**Comment by p-schlickmann** [comment]
If anyone is facing this on 2024. They've added a flag `SKIP_YARN_INSTALL`.

See: https://github.com/rails/jsbundling-rails/blob/main/lib/tasks/jsbundling/build.rake#L18C3-L18C92
