### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by dvodvo** [rails/jsbundling-rails#122]
I made the mistake of running ./bin/rails javascript:install:esbuild

The repository has no suggestions as to uninstalling and seraching the code does not reveal anything in particular.
Through prodding, most elements were captured and deleted, however the rendered HTML still returns:
```
<script type="esms-options">{"nonce":null}</script>
<script src="/assets/es-module-shims.min-b8099fffdbd758070d4801321d43b389c5b6174a50782f9f4cb57061533b7ac2.js" async="async" data-turbo-track="reload"></script>
```
which means somewhere, the es-module is being invoked.  I see some odd behaviours with subsequently pinned packages, thus would like to eliminate this source of pollution.

What can be done?

**Comment by richardkmiller** [comment]
Hi @dvodvo, version control can be really helpful here. If your codebase in question isn't versioned, you can run "rails new" in a new directory, with options matching your main code base as close as you can remember. Then commit it to version control. Then run `rails javascript:install:esbuild` again. Then run `git diff` to see what files were added or changed by esbuild and use that as your todo list to clean up your main code base.

**Comment by dvodvo** [comment]
Yes, that is effectively what I did.  Sorry about the assumption on the versioning. 

I found out that without installing esbuild, those two script tags are generated by a default new rails (7.0.3) installation .

**Comment by richardkmiller** [comment]
@dvodvo OK great! No problem!
