### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/assets/assets/application.css.map) when migrating from webpack to esbuild 

### ISSUE THREAD

**Issue by ashok-stack** [rails/jsbundling-rails#129]
i have added a comment on the rails existing rails issue page
adding it here just to double check whether it is related to jsbundling-rails
https://github.com/rails/rails/issues/44260

**Comment by dhh** [comment]
Looks like there's old assets that needs to be cleaned out with `rake assets:clean`.
