### ISSUE TITLE
overmind or foreman?

### ISSUE THREAD

**Issue by justin808** [rails/jsbundling-rails#136]
Should [overmind](https://github.com/DarthSim/overmind) be supported or preferred?

https://github.com/rails/jsbundling-rails/blob/main/lib/install/dev#L8

```
#!/usr/bin/env bash

if ! gem list foreman -i --silent; then
  echo "Installing foreman..."
  gem install foreman
fi

foreman start -f Procfile.dev "$@"
```

**Comment by dhh** [comment]
Don't think it's needed for what we're using it for. Easy enough for someone to change if they prefer.
