### ISSUE TITLE
set-script has been removed from npm 9

### ISSUE THREAD

**Issue by jcoyne** [rails/jsbundling-rails#138]
```
Add build script
         run  npm set-script build "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets" from "."
Unknown command: "set-script"
```

```
npm --version
9.0.0
```

It is used here:
https://github.com/rails/jsbundling-rails/blob/5e6758f077f0be59f94ea34678c2f8c452f2ba32/lib/install/esbuild/install.rb#L10

**Comment by pandancode** [comment]
The below should work.

`npm pkg set scripts.build="webpack --config webpack.config.js"`

Probably makes sense to include it in the codebase
