### ISSUE TITLE
Daily alerts not being delivered

### ISSUE THREAD

**Issue by ferblape** [rails/jsbundling-rails#145]
There's an issue with daily alerts, since [friday](https://populate.slack.com/archives/CJJDQ5Q87/p1674197126370279) are not being delivered.

Apart from fixing this we should:

- [ ] Document how they can be manually triggered at https://populate.getoutline.com/doc/operations-XxPMKwUJVe
- [ ] Investigate why the job stops before ending without triggering an appsignal notification

**Comment by elia** [comment]
🤔 wrong repo?
