### ISSUE TITLE
bin/dev: 8: exec: foreman: not found

### ISSUE THREAD

**Issue by Michael-Mehta** [rails/jsbundling-rails#147]
I get this error when I run bin/dev in the terminal

**Comment by Michael-Mehta** [comment]
/home/test/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/foreman-0.87.2/bin/foreman start -f Procfile.dev



That's what ended up working for me in case anyone else has the same problem, however yours might look slightly different becaue this is the route for my laptop

**Comment by BilalBudhani** [comment]
@Michael-Mehta try running `rbenv rehash` if that doesn't fix your issue then there might be problem with your `rbenv` installation.

**Comment by melashu** [comment]
Using `rbenv rehash ` works for me
