### ISSUE TITLE
yarn: not found while deployment by mina

### ISSUE THREAD

**Issue by ajahongir** [rails/jsbundling-rails#152]
hey guys, having an issue. i have setup my mina deploy, and install yarn and make global as node by nvm. 
BUT as i run deployment, i am having an issue with that `jsbundling-rails` cant find `yarn`. i guess that `jsbundling-rails` lookking for different path. but can not debug which yarn using this gem. any help will be greatly appreciated

**Comment by dhh** [comment]
yarn has to be present in your path.
