### ISSUE TITLE
How to confirm that yarn dependencies are installed? 

### ISSUE THREAD

**Issue by pughpugh** [rails/jsbundling-rails#160]
In a development environment, I'm wondering what the recommended approach is to confirm that yarn dependencies are fully up to date? I notice `esbuild` will happily build when the dependencies installed are out of date compared to the versions defined in `package.json` and it's not very obvious a `yarn install` needs to be run.

The standard seems to be a Procfile containing 

```
js: yarn build --watch
```

The best I can come up with is using `immutable-cache` to try and make it throw an error., although it's still not obvious what's gone wrong.

```
js: yarn install --immutable-cache && yarn build --watch
```

I just wanted to check I've not missed something obvious.

**Comment by dhh** [comment]
I think any of those are fine 👍
