### ISSUE TITLE
bun individual files

### ISSUE THREAD

**Issue by silva96** [rails/jsbundling-rails#188]
How can I get what I use to have using esbuild

in package.json:
```json
"scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds"
}
```
This would look like this in chrome developer tools:

![CleanShot 2024-01-18 at 12 03 49@2x](https://github.com/rails/jsbundling-rails/assets/4019924/082809f2-4152-4b73-996b-d7ca1b13de4b)

There I can add breakpoints to debug each individual stimulus controller.

Now that I'm using Bun

package.json:
```
  "scripts": {
    "build": "bun bun.config.js"
    }
```

Default generated bun.config.js

```
import path from 'path';
import fs from 'fs';

const config = {
  sourcemap: "external",
  entrypoints: ["app/javascript/application.js"],
  outdir: path.join(process.cwd(), "app/assets/builds"),
};

const build = async (config) => {
  const result = await Bun.build(config);

  if (!result.success) {
    if (process.argv.includes('--watch')) {
      console.error("Build failed");
      for (const message of result.logs) {
        console.error(message);
      }
      return;
    } else {
      throw new AggregateError(result.logs, "Build failed");
    }
  }
};

(async () => {
  await build(config);

  if (process.argv.includes('--watch')) {
    fs.watch(path.join(process.cwd(), "app/javascript"), { recursive: true }, (eventType, filename) => {
      console.log(`File changed: ${filename}. Rebuilding...`);
      build(config);
    });
  } else {
    process.exit(0);
  }
})();
```

Currently only one file in the chrome console, no individual controllers.

![CleanShot 2024-01-18 at 11 56 12@2x](https://github.com/rails/jsbundling-rails/assets/4019924/af50051a-05cd-4617-ae61-6673cc6044fe)

**Comment by pokonski** [comment]
You can provide a list of files to `entrypoints`: https://bun.sh/docs/bundler#entrypoints
