### ISSUE TITLE
esbuild plugins

### ISSUE THREAD

**Issue by jasonlor** [rails/jsbundling-rails#19]
Absolutely love this jsbundling-rails approach. This may be related/redundant to #8. 

What is the recommended approach if I wanted to use esbuild plugins?

I noticed that both rollup/webpack have config files that are added on install but not esbuild.

---

![image](https://user-images.githubusercontent.com/197345/132925481-e1ae5bb7-62ee-471c-902e-61253581a8e3.png)

**Comment by dhh** [comment]
Yes, see #8. There's a straight path to adding your own node program that uses esbuild as an API. But esbuild doesn't have an official config file structure. Let's keep the chat in #8 👍
