### ISSUE TITLE
with esbuild, how to dynamic load stimulus controllers?

### ISSUE THREAD

**Issue by xiaohui-zhangxh** [rails/jsbundling-rails#22]
I know this is a question about esbuild not jsbundling-rails, but when webpacker is replaced by jsbundling-rails, how to make it works smoothly with stimulus?

### import stimulus controllers

```javascript
import { Application } from "stimulus"

const application = Application.start()
const context = require.context("controllers", true, /_controller\.js$/)
application.load(definitionsFromContext(context))
```

### browser got this error

```
Uncaught TypeError: __require.context is not a function
    at application.source.js:2329
    at application.source.js:2331
```

**Comment by dhh** [comment]
You have to manually maintain the import list. But I’ve made that easy in stimulus-rails with a generator and a manifest updater. Have a look at the latest repo.

**Comment by xiaohui-zhangxh** [comment]
> You have to manually maintain the import list. But I’ve made that easy in stimulus-rails with a generator and a manifest updater. Have a look at the latest repo.

Oh, thanks for your reply, I don't have a chance to look at the latest stimulus-rails repo, seems it has to works with importmap.

In the past hour, I just write(copy and changed a little) a plugin to autoload stimulus controllers with esbuild. Is this ok to pull in jsbundling-rails repo?

https://github.com/rails/jsbundling-rails/compare/main...xiaohui-zhangxh:main

**Comment by dhh** [comment]
The stimulus-rails gem works with both sprockets and jsbundling-css. The manifest and generator setup works specifically for esbuild style setups. No intention to add plugins to esbuild here. But feel free to add something on the side 👍

**Comment by Intrepidd** [comment]
FYI there already is a plugin for loading stimulus controllers with esbuild : https://github.com/zombiezen/esbuild-plugin-stimulus it didn't work properly with deeply nested controllers but a recent fix made it similar to the webpack helpers :)

**Comment by dhh** [comment]
Happy to have that as a side option, but I don't think it's valuable enough over a generated list to be the default.
