### ISSUE TITLE
The precompile task fails to move js files to the public directory if they did not exist already

### ISSUE THREAD

**Issue by brenogazzola** [rails/jsbundling-rails#23]
While testing other PRs, I've noticed that the `assets:precompile` fails to move files from the `build` directory to the `assets` directory, if the `build` directory was empty (did not run `yarn build --watch` before)

#### Reproduction: 

Running inside `rails-dev-box`
```
cd ..
mkdir demo
cd demo

../rails/railties/exe/rails new mega --dev -j webpack
rm -rf app/assets/builds/* public/assets public/packs 
RACK_ENV=production RAILS_ENV=production bin/rails assets:precompile
```

#### Result
```
app/assets/builds/actioncable-[hash].js
app/assets/builds/application.js

public/assets/actioncable-[hash].js
public/assets/actioncable.esm-[hash].js
public/assets/actiontext-[hash].js
public/assets/activestorage-[hash].js
public/assets/activestorage.esm-[hash].js
public/assets/manifest-[hash].js
public/assets/stimulus@3.0.0-beta.2-[hash].js
public/assets/stimulus-autoloader-[hash].js
public/assets/stimulus-[hash].js
public/assets/stimulus-importmap-autoloader-[hash].js
public/assets/trix-[hash].js
public/assets/turbo-[hash].js
```

You can see the `application.js` was not moved. It is also not listed in `.sprockets-manifest`. This means that `javascript_include_tag` cannot find it.

However... if I do `assets:precompile` again:
```
$ webpack --config webpack.config.js
assets by status 7.78 KiB [cached] 1 asset
asset application.js 95.8 KiB [compared for emit] [minimized] (name: application)
orphan modules 189 KiB [orphan] 15 modules
runtime modules 6.75 KiB 9 modules
cacheable modules 190 KiB
  ./app/javascript/application.js + 7 modules 173 KiB [built] [code generated]
  ./node_modules/@rails/actioncable/src/index.js + 8 modules 16.8 KiB [built] [code generated]
webpack 5.52.1 compiled successfully in 2163 ms
Done in 2.99s.
I, [2021-09-13T13:17:01.433519 #146072]  INFO -- : Writing /vagrant/demo/mega/public/assets/actioncable-a9fcb0bc8b59438ae97a7b2e98a4160c8a7075e52e73ae5ac605ef1ab23748cb.js
I, [2021-09-13T13:17:01.433902 #146072]  INFO -- : Writing /vagrant/demo/mega/public/assets/actioncable-a9fcb0bc8b59438ae97a7b2e98a4160c8a7075e52e73ae5ac605ef1ab23748cb.js.gz
I, [2021-09-13T13:17:01.434675 #146072]  INFO -- : Writing /vagrant/demo/mega/public/assets/application-82f15c75ea5d419d0cad09eed8beb84807bfbd5741fae8b7bc8c0ae209a6bded.js
I, [2021-09-13T13:17:01.435301 #146072]  INFO -- : Writing /vagrant/demo/mega/public/assets/application-82f15c75ea5d419d0cad09eed8beb84807bfbd5741fae8b7bc8c0ae209a6bded.js.gz
```

There they go. This time the missing files are moved and everything works.

**Comment by dhh** [comment]
I think it was due to the wrong gitignore configuration. Fixed that now.

**Comment by dhh** [comment]
Fixed in 0.1.5 (but of course you need to fix yourself if you already ran the installer).

**Comment by minimul** [comment]
fwiw I had a similar case with jsbundling with Rails 6 in that application.js was not being copied over to `public/assets` on a fresh build using `asset:precompile`.

My .gitignore was correct but I didn't have `app/assets/builds/.keep`. This fixed the problem and yes I didn't run the installer initially.

**Comment by dukz** [comment]
For anybody there that didn't initially understand what minimul said, the fix was to add the `app/assets/builds/.keep` file into the repository so that the `assets:precompile` doesn't ignore that directory altogether.

```bash
touch app/asets/builds/.keep
```

Git stage and commit that file.
