### ISSUE TITLE
Add Vite as option for JS bundling

### ISSUE THREAD

**Issue by Juice10** [rails/jsbundling-rails#25]
I really love the excellent work that is being done allowing people to move over from webpack to esbuild and rollup. 

I'm seeing a lot of effort going in to supporting esbuild and rollup as two options with both their own pros and cons. There is however a way you can have your cake and eat it too with [Vite](https://vitejs.dev).

It's a build tool built by the creator of Vue that has a great momentum, it combines both esbuild for dev (speed), and rollup for production (backwards compatibility). And it's aim is to "provide a faster and leaner development experience for modern web projects" which fits well with rails.

Vite is a lot more convention over configuration compared to other builders. And it has official support for a wide array of popular javascript frameworks, [super fast hot module reload even on huge projects](https://vitejs.dev/guide/features.html#hot-module-replacement) and [other developer ergonomics](https://vitejs.dev/guide/features.html). And there are a of community plugins and templates.

There is even a rails gem to get it working with rails I've been using [vite-rails](https://vite-ruby.netlify.app/guide/rails.html) for a while instead of webpacker and I couldn't be happier!

Honestly I rolled my eyes once I saw _yet another javascript build tool_, but since Vite doesn't try to reinvent the wheel, just bring together the best of the latest generation of build tools in a package that is easy to use and easy to setup I think this has the potential to be a great default rails/javascript build tool for people doing React, vue angular etc.

More info:
[Why Vite?](https://vitejs.dev/guide/why.html)
[How does it compare to X?](https://vitejs.dev/guide/comparisons.html)

**Comment by chloerei** [comment]
In order to use HMR, assets should be serve by vite dev server, so vite-rails is the solution.

refer https://github.com/rails/jsbundling-rails/blob/main/docs/comparison_with_webpacker.md

**Comment by rmacklin** [comment]
I'm doing some spikes to address the current limitations I documented there, and I'm optimistic that we can close that gap, ideally simultaneously adding support for other options (e.g. snowpack)

**Comment by dhh** [comment]
vite-rails looks to have much grander ambitions than what fits this gem. jsbundling-rails is here to provide the most basic configuration possible of popular bundlers, and then have them compile into app/assets/builds. I think vite is trying to do a lot more than that. Which is totally great, just not something that easily fits under the jsbundling-rails umbrella. But it also doesn't have to. We're never going to arrive at The One Way to do JavaScript (in Rails or elsewhere).

**Comment by chmich** [comment]
Vite is a slimmer shakapacker and i think it will making the race.

**Comment by adenta** [comment]
_if_ vite continues to be _the_ way the javascript kiddos do javascript, when would we incorporate it into this gem?
