### ISSUE TITLE
Move JavaScript default directory back to app/assets/javascripts ?

### ISSUE THREAD

**Issue by chloerei** [rails/jsbundling-rails#26]
When sprockets and webpacker coexist, `/app/javascript` can avoid conflicts.

Now JavaScript is back to the management of Asset Pipeline, it seems more reasonable to set the default directory to `app/assets/javascripts`.

Just an idea, may be a lot of work to consider.

**Comment by dhh** [comment]
I think we're better off having a single place for JavaScript to live regardless of which method you use to deliver it. Gives a uniform place for generators and installers to target.
