### ISSUE TITLE
Glob syntax not supported for Windows out of the box [with esbuild]

### ISSUE THREAD

**Issue by JenteSL** [rails/jsbundling-rails#28]
Currently, the `build` script involves: `esbuild app/javascript/*.* --bundle --outdir=app/assets/builds`

On Windows, this results in an error: `Could not resolve "'app/javascript/*.*'" (glob syntax must be expanded first before passing the paths to esbuild)`.

From what I've found troubleshooting, it appears that the glob syntax is a shell-specific feature. [esbuild does not interpret it on its own.](https://github.com/evanw/esbuild/issues/976#issuecomment-799719406) With PowerShell or CMD on Windows not supporting the glob syntax properly, the `build` commands doesn't work out of the box in these shell environments.

I'm not sure how to go on from here for a general solution. For now, in my project I changed the `build` script to reference the only `.js` file I have: `esbuild app/javascript/application.js --bundle --outdir=app/assets/builds`

**Comment by dhh** [comment]
Would be nice to have a section in the README about Windows considerations 👍

**Comment by dhh** [comment]
We could actually also detect Windows in the install script and change the default build script proposed. Feel free to have a look at that if you'd like!

**Comment by JenteSL** [comment]
Yeah, the only problem is that I'm not sure which command could do the trick on Windows, without specifying all the js files.

I'm not sure it is possible without an esbuild config file and something like an external [glob](https://www.npmjs.com/package/glob) package...

**Comment by dhh** [comment]
Documented it via https://github.com/rails/jsbundling-rails/commit/95e6b15d02153e852712212c666af17a45f45d15
