### ISSUE TITLE
Allow to use `npm` instead of `yarn`

### ISSUE THREAD

**Issue by gosukiwi** [rails/jsbundling-rails#3]
Hi guys, is there a way to use `npm` instead of `yarn` with this gem? I can't find any info about that in the README.

**Comment by dhh** [comment]
There is not at this time. But probably would be nice to at least catch if yarn isn't available on the system, then try npm. Do have a look at that, if there's a simple path to do so.

**Comment by czj** [comment]
Node.js 16 became the current version in april 2021 and will become LTS on october 21st. Source : https://medium.com/the-node-js-collection/node-js-16-available-now-7f5099a97e70

As npm 7 is now as fast/clean/silent as yarn for install tasks, being able to switch to it would prevent installing one more package, which is always nice :-)

**Comment by arambert** [comment]
Hi,
Today `yarn` is still required. It feels like an excessive requirement. It would be nice to be able to use `npm`.
