### ISSUE TITLE
Abort install or detailed info message when NPX < 7.1

### ISSUE THREAD

**Issue by thomasvanholder** [rails/jsbundling-rails#35]
Installing `jsbundinling-rails` without previously upgrading npx to (>= 7.1) returns the error below when trying to set the build scripts in package.json. This is briefly mentioned in the README: __You will also need npx version 7.1.0 or later.__

```bash
npm@6.14.15 /usr/local/lib/node_modules/npm

Did you mean this?
    run-script
```

To help a successful install, the user could be informed: 
- by adding a more informative / actionable info message that checks at the beginning of the install script the currently installed npx version
- or by aborting the install script as it will need to be run again after upgrading NPX to (>=7.1).

Although, I don't have any experience in building engines with thor, I gave it a short try and something like below could work if it's being inserted before the right install script.  Any feedback is welcome.

```ruby
require 'open3'

say "Checking node version"

stdout, _stderr, _status = Open3.capture3("npx -v")

npx_version = stdout.match(/\d.\d+/).to_s.to_f

unless npx_version >= 7.1
  abort "Upgrade npx to version 7.1 or later", :red
end
```

This could be applied to `cssbunding-rails` too.

**Comment by tabishiqbal** [comment]
Ran into this myself yesterday and spent a bit of time trying to figure out what the issue was.  A check def would be helpful!

**Comment by SkipKayhil** [comment]
I think a better solution may be to add the scripts field using a parse/dump of package.json in ruby instead of using npm.

@dhh, does this sound reasonable? If so I can create a PR

**Comment by dhh** [comment]
Not keen on replicating npx functionality here. We're trying to keep these gems as simple as possible. But I do agree that we should have a clear error message as to what the problem is, and how to correct it.
