### ISSUE TITLE
Can this just be a generator?

### ISSUE THREAD

**Issue by ryanb** [rails/jsbundling-rails#36]
Both `jsbundling-rails` and `cssbundling-rails` do little outside of the initial generation. Is the `rake` task enhancements the only other behavior? If so, could you add that rake task to the generator? This removes the gems as a required dependencies and allows for customization of the rake task.

For example, I removed the gems and added this rake file.

```
namespace :yarn do
  desc "Build your JavaScript & CSS"
  task :build do
    system "yarn run build"
  end
end

Rake::Task["assets:precompile"].enhance(["yarn:build"])
```

I changed the yarn `build` script to build both js and css and added other yarn scripts to handle the watch behavior.

I'm not suggesting that rake task be the default, just that moving it into the generator gives us the flexibility of customizing it to best fit the project.

**Comment by dhh** [comment]
You can always just overwrite the rake tasks in your own app. And then even delete the gem dependencies, if you're all set to just follow the conventions. But on the other hand, what's the big upside if you're not doing any specialization? 

It would strike me as a more difficult story to tell that first you add the gems, run the installers, then copy over some code. And if any of this changes going forward, which the precompile step might well, then you have to manually copy and paste again.

The price of a tiny dependency doesn't seem to be refunded by that approach in my analysis. But it's great that it's possible!

**Comment by ryanb** [comment]
> It would strike me as a more difficult story to tell that first you add the gems, run the installers, then copy over some code

My thinking is the installer would generate the rake task file so there's no additional steps. It seems a bit strange that it's the only code that's not generated, while similar files like `bin/dev` are.

> The price of a tiny dependency doesn't seem to be refunded by that approach in my analysis. But it's great that it's possible!

I'll close this since there probably isn't much need for it. Just wanted to check.

**Comment by dhh** [comment]
I think it's a fair debate! There really ISN'T much here. At the very least, we should document that you don't need to have persistent dependencies, if you'd rather not. That it doesn't take much to dump them.

That's the beauty of this new approach. It really just let's JS do its thing, then hands over to the existing setup for the asset pipeline.
