### ISSUE TITLE
Support non-JS bundlers?

### ISSUE THREAD

**Issue by domchristie** [rails/jsbundling-rails#4]
I’ve often found that using a bundler’s CLI along with a `package.json` `build` script is the most transparent way to build assets: input / output files are clearly defined, making it easy to know what’s going on. **jsbundling-rails** looks like a great interface for managing JS bundlers in this way, but I’m wondering if it’s scope could be expanded to install non-JS builders.

For example, installing and running a Tailwind builder follows a very similar pattern to the JS builders: 
1. Add a package.json with a build script
2. Add a tailwind.config.js specifying JIT mode and purge options
3. Add the tailwind.css manifest

This looks something like: https://github.com/rails/jsbundling-rails/compare/main...domchristie:tailwind

One potential problem: running more than one build script might get messy, particularly with a `—watch` option?

Edit: and another: preventing installations from clobbering package.json

**Comment by dhh** [comment]
I totally had that in mind when changing from app/assets/esbuilds to app/assets/builds. Love this for idea of making it work for TW as well. Although given how little code there actually is in this gem, we may also just consider putting it in a sister gem (like I originally had with esbuild-css and rollupjs-rails). Perhaps cssbundling-rails? Then we could have installers for Dart Sass, TW, plain PostCSS?

**Comment by dhh** [comment]
It's happening:  https://github.com/rails/cssbundling-rails

**Comment by domchristie** [comment]
@dhh FWIW a couple of more generic naming options: assetbundling-rails or nodebundling-rails? `asset` may conflict with the asset pipeline tasks, but `rails node:install:PACKAGE`, might work?

**Comment by dhh** [comment]
There's so little here that I don't think we need to package everything together in one gem. I think keeping the JS and CSS separate makes sense. The main insight here is that we can get these great integrations very cheaply by using the asset pipeline for delivery of builds.

**Comment by dhh** [comment]
Also fixed the clobbering of package.json in cssbundling-rails. Need to bring that here too.
