### ISSUE TITLE
Esbuild Configuration for Javascript Debugging

### ISSUE THREAD

**Issue by ToolKami** [rails/jsbundling-rails#40]
Migrated from Webpacker to Esbuild using jsbundling-rails and it seems like Javascript debugging no longer works for either VSCode nor Rubymine.

This is the ESBuild settings I am using.
```
require("esbuild").build({
  entryPoints: ["application.js", "administrate.js"],
  bundle: true,
  outdir: path.join(process.cwd(), "app/assets/builds"),
  absWorkingDir: path.join(process.cwd(), "app/javascript"),
  watch: watch,
  plugins: [ImportGlobPlugin()],
}).catch(() => process.exit(1));
```

**Comment by ToolKami** [comment]
For more context.

The compiled assets can be found in `app/assets/builds/*.js` or `public/assets/**/*.js`.

The bundled JS that is actually loaded is http://localhost:3000/assets/application.debug-fc91062bf3c7540aaa82649048a601114b102e175ab6b54a445960fb29a8ebc2.js.

but I'm also seeing this warning:
`
DevTools failed to load source map: Could not load content for http://localhost:3000/assets/application.js-9bc83b28e900922b5437611c775ac156746a4b54b883ec28346dc6ee1be3bc3b.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
`

**Comment by dhh** [comment]
Source mapping is still not fully supported. Need alterations to Sprockets.

**Comment by czj** [comment]
While sprockets is not compatible, you can setup a custom route like so:

```ruby
if Rails.env.development?
  redirector = ->(params) { ApplicationController.helpers.asset_path(params[:name].split("-").first.append(".map")) }
  constraint = ->(request) { request.path.ends_with?(".map") }
  get "assets/*name", to: redirect(redirector), constraints: constraint
end
```

If the assets pipeline cannot find a file corresponding to the a given sourcemap file name, Rails' routing will pick up any URL ending in `.map` and redirect to the URL of the corresponding `.css.map` file in the asset pipeline.

Works well for us with `jsbundling-rails` and `css-bundling-rails`. Maybe it also works with propshaft.

**Comment by jhirn** [comment]
Figured I'd share my esbuild file as I've been working on it for a few weeks now and had to dig for a lot of this myself. The inline sourcemaps are not ideal for production but they work for now. Also svgr, loader, injecting shims and adding watch was a bit tricker than I hoped for but well worth it so far. Hopefully this helps someone. 

```javascript
#!/usr/bin/env node

const glob = require('glob')
const esBuild = require('esbuild')
const svgrPlugin = require('esbuild-plugin-svgr')

const watch = process.argv.includes('--watch')
const minify = process.argv.includes('--minify')

const watchOptions = {
  onRebuild: (error, result) => {
    if (error) {
      console.error('watch build failed:', error)
    } else {
      console.log(result)
      console.log('watch build succeeded. ')
    }
  }
}

const svgrOptions = {
  typescript: false
}

const loaders = {
  '.png': 'file'
}

glob('app/javascript/**/*.*', {}, (_res, files) => {
  esBuild.build({
    entryPoints: files,
    bundle: true,
    outdir: 'app/assets/builds',
    plugins: [
      svgrPlugin(svgrOptions)
    ],
    watch: watch && watchOptions,
    sourcemap: 'inline',
    loader: loaders,
    publicPath: '/assets',
    inject: ['.esbuild/shims/react-shim.js'],
    minify
  }).then(result => {
    console.log(result)
    if (watch) {
      console.log('Build finished, watching for changes...')
    } else {
      console.log('Build finished, Congrats')
    }
  }).catch(result => {
    console.log(result)
    process.exit(1)
  })
})
```

**Comment by dhh** [comment]
Sourcemaps generated by esbuild (or any other transpiler) are now supported since [sprockets-rails 3.4.0](https://github.com/rails/sprockets-rails/releases/tag/v3.4.0).

**Comment by TastyPi** [comment]
I switched to `jsbundling-rails` recently and came across this issue, despite having sprockets-rails 3.4.2. Esbuild is creating the *.js.map files, but then the browser complains that it can't find `[name].js-[contenthash].map`.

**Comment by dhh** [comment]
Can you try to produce an example app that triggers this? It's working for me when I try.

**Comment by jaredcwhite** [comment]
FWIW, source maps via esbuild -> Sprockets working for me as well. 👍

**Comment by fcheung** [comment]
Just hopping in here to say that setting `config.assets.debug` to false  (used to default to true in dev, doesn't for apps generated after https://github.com/rails/rails/commit/adec7e7ba87e3d268149d0020d54dc211eb02ada#diff-2d045bcceb384e942cad5480ff01eff82255819f8944bef7a03e1609cc949004 ) fixed this for me

with config.assets.debug set to true, the AddSourceMapCommentToAssetProcessor ( https://github.com/rails/sprockets/blob/24c97270fbf6de11b4ffff0311bb427b7a8a3a83/lib/sprockets/add_source_map_comment_to_asset_processor.rb) processor in sprockets appends a second, incorrect source map comment

**Comment by TastyPi** [comment]
Setting `config.assets.debug = false` fixed it for me too, thanks @fcheung!

**Comment by WriterZephos** [comment]
@dhh I think this is still an issue, but it's intermittent. Just randomly stopped working after I made a change to a stimulus controller. Tried the `config.assets.debug = false` fix but it didn't work for me.

**Comment by danieldocki** [comment]
I was having the same problem with migrating from webpacker to jsbundling-rails with esbuild, every time I changed a js file the css file lost the styles.

Then I noticed that some js files were doing:

```
import 'something.css'
```

I removed all of them from the js files and it seems it solved my problem, I don't know if it has anything to do with this situation.

**Comment by jaredcwhite** [comment]
> I removed all of them from the js files and it seems it solved my problem, I don't know if it has anything to do with this situation.

@danieldocki yeah that's a known issue. see: https://github.com/rails/jsbundling-rails#why-does-esbuild-overwrite-my-applicationcss

**Comment by nachoal** [comment]
I'm currently in the middle of migrating a `7.0.2.3` rails app from webpack to jsbuild and started having the `DevTools failed to load source map` error. 

After checking the following:
> Sourcemaps generated by esbuild (or any other transpiler) are now supported since [sprockets-rails 3.4.0](https://github.com/rails/sprockets-rails/releases/tag/v3.4.0).

My sprockets version is `3.4.2` but the issue still exists, after trying @fcheung solution
`config.assets.debug = false` the warning message stopped happening.

If someone can explain why this is happening or guide me in the right direction to be able to have debug = true it would be awesome, ty!

**Comment by jhirn** [comment]
@nachoal, Can't guarantee help but if you could share your esbuild script/config as well as any other relevant asset configuration that would help to diagnose your problem I'll take a look.

**Comment by nachoal** [comment]
Thanks @jhirn 

`package.json`:

```
{
  "name": "x",
  "private": true,
  "dependencies": {
    "@hotwired/stimulus": "^3.0.1",
    "@hotwired/turbo-rails": "^7.1.3",
    "@rails/actioncable": "^6.0.5",
    "@rails/actiontext": "^6.0.5",
    "@rails/activestorage": "^6.0.5",
    "@rails/ujs": "^6.0.5",
    "autoprefixer": "^10.4.7",
    "esbuild": "^0.14.48",
    "postcss": "^8.4.14",
    "stimulus": "^3.0.1",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat",
    "trix": "^2.0.0-beta.0"
  },
  "version": "0.1.0",
  "devDependencies": {},
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets"
  }
}

```

`Procfile.dev`

```
web: bin/rails server
jobs: bin/sidekiq
css: bin/rails tailwindcss:watch
js: yarn build --watch
```

Having `config.assets.debug = true`

**Comment by nachoal** [comment]
> While sprockets is not compatible, you can setup a custom route like so:
> 
> ```ruby
> if Rails.env.development?
>   redirector = ->(params) { ApplicationController.helpers.asset_path(params[:name].split("-").first.append(".map")) }
>   constraint = ->(request) { request.path.ends_with?(".map") }
>   get "assets/*name", to: redirect(redirector), constraints: constraint
> end
> ```
> 
> If the assets pipeline cannot find a file corresponding to the a given sourcemap file name, Rails' routing will pick up any URL starting with `/assets/` and ending in `.map` and redirect to the URL of the corresponding `.css.map` or `.js.map` file in the asset pipeline.
> 
> Works well for us with `jsbundling-rails` and `cssbundling-rails`. Maybe it also works with propshaft.

Had to modify this approach a little bit, here's the one that's staying: 

```
if Rails.env.development?
    redirector = ->(params, _) { ApplicationController.helpers.asset_path("#{params[:name].split('-').first}.map") }
    constraint = ->(request) { request.path.ends_with?(".map") }
    get "assets/*name", to: redirect(redirector), constraints: constraint
 end
```

**Comment by ccastillop** [comment]
I've spent few hours struggling with this. 

Setting `config.assets.debug = false` on `config/environments/development.rb` did not add expected `//# sourceMappingURL=application.js.map`  url on `assets/application.js`

ThenI set `config.assets.debug = true` on `config/environments/development.rb` and expected `//# sourceMappingURL=application.js.map` showed but `DevTools failed to load source map`

At the end I added suggested https://github.com/rails/jsbundling-rails/issues/40#issuecomment-1176856408 to `routes.rb ` and It worked.

**Comment by salimhb** [comment]
For some reason [Sprockets 4.2.0](https://github.com/rails/sprockets/blob/main/CHANGELOG.md) breaks this for me.
The workaround in routes.rb is not catching the sourcemap request anymore.
```
ActionController::RoutingError (No route matches [GET] "/application.js-ed5ef27ac34ec75105c2c5f54bcfb407a5ecceb43da87cfe9437f57c9cf55d45.map"):
```
I'm not sure which [change](https://github.com/rails/sprockets/compare/v4.1.1...v4.2.0) exactly affects this.

I downgraded back to 4.1.1 to get sourcemaps working again.

**Comment by navidemad** [comment]
I'm getting this `No route match error` since this commit https://github.com/rails/sprockets/commit/06925180af205000b689345061cfa62faad85ad6

**Comment by gap777** [comment]
Sprockets 4.2.0 also broke sourcemaps for me (esbuild + Rails 7.0.4.1). `config.assets.debug` doesn't seem to help either way. @dhh?

**Comment by kkurcz** [comment]
Has anyone found a fix for this?

**Comment by scratchoo** [comment]
sourcemap is working (Rails 7.0.3.1) however the console show the wrong stimulus controller name, the logged line is correct, only the file name is not, really weird!

**Comment by gap777** [comment]
@dhh This seems to have recently broken for @salimhb , @kkurcz  and myself (at least). 
Any ideas or workarounds?

**Comment by alexandrepalma** [comment]
Here's what worked for me on Rails 7.0.4.3, since the redirection route approach didn't work.
Create the following file:

app/middleware/sourcemap_redirect_middleware.rb
```ruby
class SourcemapRedirectMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    if env['PATH_INFO'].match?(/.*\.(js|css)-.*\.map/)
      asset_name = env['PATH_INFO'].split('-').first
      new_path = ActionController::Base.helpers.asset_path("#{asset_name}.map")

      # Preventing redirection loop
      if env['PATH_INFO'] != new_path
        return [301, { 'Location' => new_path }, []]
      end
    end

    @app.call(env)
  end
end
```
have your development.rb configured like this:
```ruby
  require_relative '../../app/middleware/sourcemap_redirect_middleware'
  config.middleware.use SourcemapRedirectMiddleware
  config.assets.debug = true
```
Hope it works for you guys!

**Comment by lreardon** [comment]
> Here's what worked for me on Rails 7.0.4.3, since the redirection route approach didn't work. Create the following file:
> 
> app/middleware/sourcemap_redirect_middleware.rb
> 
> ```ruby
> class SourcemapRedirectMiddleware
>   def initialize(app)
>     @app = app
>   end
> 
>   def call(env)
>     if env['PATH_INFO'].match?(/.*\.(js|css)-.*\.map/)
>       asset_name = env['PATH_INFO'].split('-').first
>       new_path = ActionController::Base.helpers.asset_path("#{asset_name}.map")
> 
>       # Preventing redirection loop
>       if env['PATH_INFO'] != new_path
>         return [301, { 'Location' => new_path }, []]
>       end
>     end
> 
>     @app.call(env)
>   end
> end
> ```
> 
> have your development.rb configured like this:
> 
> ```ruby
>   require_relative '../../app/middleware/sourcemap_redirect_middleware'
>   config.middleware.use SourcemapRedirectMiddleware
>   config.assets.debug = true
> ```
> 
> Hope it works for you guys!

Worked for me, thank you @alexandrepalma

**Comment by lreardon** [comment]
@alexandrepalma's solution worked for me.

**Comment by gap777** [comment]
Worked for us, too... but found out that we needed a backtrace silencer to preserve stack traces:

```
# config/initializers/backtrace_silencers.rb
Rails.backtrace_cleaner.add_silencer { |line| line.include?('app/middleware') }
```

**Comment by navidemad** [comment]
Hello guys, any update regarding this issue ?
Have a great day

**Comment by navidemad** [comment]
up

**Comment by gap777** [comment]
Is this fixed with Rails 7.2.1?

**Comment by kkurcz** [comment]
@gap777 if you find a definitive solution please let me know

**Comment by bsoglin** [comment]
Still an issue

**Comment by salimhb** [comment]
I got this working again using a different approach because Firefox doesn't follow redirects when loading a source map. I added a controller action to resolve this

In a `pages_controller.rb`
```ruby
  def source_map
    file_path = Rails.root.join("app/assets/builds", "#{params[:name].split("-").first}.map")
    if File.exist?(file_path)
      send_file file_path, type: "application/json", disposition: "inline"
    else
      head :not_found
    end
  end
```
In `routes.rb`
```ruby
  if Rails.env.development?
    constraint = ->(request) { request.path.ends_with?(".map") }
    get "assets/*name", to: "pages#source_map", constraints: constraint
  end
```
