### ISSUE TITLE
add foreman into the gemfile

### ISSUE THREAD

**Issue by jcoyne** [rails/jsbundling-rails#44]
I installed this in a project and committed the results. My colleague pulled the project and tried to run `bin/dev` and he encountered a problem because he did not have foreman installed.

Should this line:
https://github.com/rails/jsbundling-rails/blob/main/lib/install/install.rb#L41

Instead be:

```ruby
gem 'foreman'
```

So that the gem is installed in the Gemfile?

**Comment by brenogazzola** [comment]
The maintainers of Foreman explicitly say that foreman should not be in the Gemfile. You are supposed to install it manually.

**Comment by dhh** [comment]
Added a catch if the global foreman is missing to install it on first use of bin/dev.
