### ISSUE TITLE
jsbundling with esbuild generated application.css that override the one from cssbundling with sass

### ISSUE THREAD

**Issue by phanhaiquang** [rails/jsbundling-rails#45]
Hi,

I used jsbundling with esbuild. At the install rake task, it shows me a "build" command to put to package.json. 

Then, I used cssbundling with sass and it also give me a "build:css" run string that should be put to package.json. 

It means that I have "build" and "build:css" script run strings in package.json. I used the default ones that was displayed by install step. 

Then, I realized that both run strings generate application.css inside app build. If I edit a scss file, then application.css was generated by "build:css". But if I edit a "js" file, then application.css was generated by "build". I don't know that esbuild could generate a css. 

Then, I change the runstring of "build:css" to generate another filename and it works fine together. 

I think that we may include this in readme or a doc.

Thanks,

**Comment by dhh** [comment]
Documented this for now: https://github.com/rails/jsbundling-rails/commit/928868ec226eda914c8ba801b94351b949cf9bf4
