### ISSUE TITLE
Asset URLs in JavaScript files

### ISSUE THREAD

**Issue by tobyaherbert** [rails/jsbundling-rails#48]
Hey!

I'm using Vue.js in a project and I can't figure out how to reference image files managed by the asset pipeline in the templates. Is there a recommended way to do this?

I understand that the bundling phase occurs before the asset pipeline does anything, so is there anything like a special URL I can put in the template which the asset pipeline rewrites later?

I've also encountered this issue with `cssbundling-rails` and wondered if a similar solution might be available?

Thanks!

**Comment by dhh** [comment]
The CSS issue is handled via Sprockets via https://github.com/rails/sprockets-rails/pull/476 (and Propshaft).

We need separate JS package that can read the digest output of Sprockets (and Propshaft) and give you the URL back. It's just a JSON file.

**Comment by tobyaherbert** [comment]
Ah, right. I'll take a look at that CSS PR.

Thanks!

**Comment by dhh** [comment]
sprockets-rails 3.3.0 will translate `url()` calls in regular css to asset digested versions: https://github.com/rails/sprockets-rails/releases/tag/v3.3.0

**Comment by dhh** [comment]
We'll tackle this issue in Sprockets and Propshaft.
