### ISSUE TITLE
Task to remove JS builds might break apps on PaaS like heroku

### ISSUE THREAD

**Issue by Intrepidd** [rails/jsbundling-rails#51]
According to the sprockets doc : 

```
rake assets:clean

Only removes old assets (keeps the most recent 3 copies) from public/assets. Useful when doing rolling deploys that may still be serving old assets while the new ones are being compiled.
```

PaaS like heroku run this task to keep things tidy.

Now with commit 8b4d2a95bc4bf5c5d590813242ac8f0aee0567fc this task will completely remove JS files from the builds directory, which is unexpected. This broke my deployment and I had to revert the gem to its previous version.

I suspect many people will have the same issue, should we rather just not enhance `assets:clean` with `javascript:clean` ?

**Comment by dhh** [comment]
Like the idea of just not enhancing for now. Want to PR that?

**Comment by Intrepidd** [comment]
Sure thing ! #52
