### ISSUE TITLE
Sprockets::DoubleLinkError: Multiple files with the same output path cannot be linked ("application.js")

### ISSUE THREAD

**Issue by erosinlove** [rails/jsbundling-rails#56]
I got this issue after add **gem 'jsbundling-rails', '~> 0.2.2'** to my application

rake aborted!
Sprockets::DoubleLinkError: Multiple files with the same output path cannot be linked ("application.js")
In "/Users/xx/xxx/app/assets/config/manifest.js" these files were linked:
  - /Users/xx/xxx/app/assets/javascripts/application.js
  - /Users/xx/xxx/app/assets/builds/application.js

Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

Please advise how can I fix this

**Comment by dhh** [comment]
You have to rename one of the two files. They're both being generated at the same path which doesn't work. Normally if you use builds/application.js you don't also need app/assets/javascripts/application.js.
