### ISSUE TITLE
The wrong order of invoking

### ISSUE THREAD

**Issue by solilin** [rails/jsbundling-rails#60]
Guys, I have a very strange problem

When I deploy a project and run `RAILS_ENV=production rails assets:precompile` the order of invoking is

```
Invoke assets:precompile (first_time)
Invoke assets:environment (first_time)
Execute assets:environment
Invoke environment (first_time)
Execute environment
Invoke css:build (first_time)
Execute css:build
Invoke javascript:build (first_time)
Execute javascript:build
✨  Done in 0.25s.
Execute assets:precompile
```

And there are no application.css and application.js files in the `assets` folder. As I understand, it is because when assets:precompile was invoking, the `builds` folder was empty.

But if I run yarn:build at first manually, then everything is good.

**Comment by solilin** [comment]
I understood where was a problem. I think it is a good idea to add to the README that you have to have an empty `builds` folder in the repo.

**Comment by marckohlbrugge** [comment]
Thanks for sharing this. This solved my issue

**Comment by rstacruz** [comment]
If anyone runs into this issue, the result is that any files build by Webpack (or whatever tool you choose) **will not be compiled by Rails on assets:precompile**.

The solution is to create an empty file (eg, `.gitkeep`) and commit that to the repository:

```sh
mkdir -p app/assets/builds/
touch app/assets/builds/.gitkeep

echo "! app/assets/builds/.gitkeep" >> .gitignore
```
