### ISSUE TITLE
esbuild does not print error messages wait failing to generate .map

### ISSUE THREAD

**Issue by Vorkosigan76** [rails/jsbundling-rails#69]
Using Rails 7.0.1 and esbuild to compile my javascript, 
`$ esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --watch`

does not always generate an application.js.map alongside application.js. When it fails, it doesn't output any error message that would allow troubleshooting.

**Comment by dhh** [comment]
That sounds like an esbuild issue. Try reporting there with the best reproduction steps you can produce 👍
