### ISSUE TITLE
Support for building engine assets

### ISSUE THREAD

**Issue by insitingcom** [rails/jsbundling-rails#7]
I've noticed this gem and the potential it will bring to Rails 7. This is probably not the right place to ask but many of us are probably wondering if these changes in asset compilation will have a positive effect on engine development.

In the past we could store all of the JS inside our engine (potentially wrapped in a gem) and they would be picked up pretty easily by sprockets. With the introduction of webpacker this was made virtually impossible. We currently have to resort to wrapping all assets in a node module and distribute them via yarn/npm which adds a lot of overhead. Most of the times the JS inside an engine has no use outside of it. Because it's so tightly coupled we'd like to go back to the early experience of just being able to import it as if it's living inside of our main application. 

Are there any plans to integrate something like this for the release of Rails 7?

**Comment by dhh** [comment]
I wish there was a good answer here, but I haven't found one. This is one of the big advantages with using Sprockets directly, like the default new setup with import maps do. The assets included can be part of the gem, and they don't have to be published to npm.

Maybe someone will come up with a good idea, but this has been an issue for years with Webpacker. So I'm not sure they will.

The upside is that for the new default Rails experience with import maps, this is a solved problem. You can pin JS dependencies from the Sprockets load path directly in your engine definition.
