### ISSUE TITLE
Sourcemaps with esbuild not working.

### ISSUE THREAD

**Issue by ioev** [rails/jsbundling-rails#73]
I'm actually not sure if this is a problem with jsbundling-rails or bundler, but:

I'm bundling my js/css via `esbuild --bundle --watch --sourcemap` which results in 2 files being generated in assets/builds, application.js and application.js.map.  The application requests these via:
/assets/application.debug-1caabe86ba2a00618598d8d7d5a8fe6c57a594dd7babeec3fe6e3ff3ce9185e1.js
/assets/application.js-4112a73edf43c31165109b2906c7bcda25ff0505d405213d39501087ea154f74.map

The sourcemap url does not exist.

If I look at the bottom of my application.js in the build folder, it ends with:
```
//# sourceMappingURL=application.js.map
```

And if I look at the end of the file coming from a server request, it ends with:
```
//# sourceMappingURL=/assets/application.js-5673ea8258e5021fb9befebfe3f84d5c8ff21ee5fd1e52b4f54b8347a5bbfbbb.map
//!
;

//# sourceMappingURL=application.js-4112a73edf43c31165109b2906c7bcda25ff0505d405213d39501087ea154f74.map
```

The first source map url works, the second does not.  I'm assuming bundler is somehow fixing the existing sourcemap definition, but then also adding it's own?

Running esbuild without --sourcemaps ends up with sourcemaps that work on the client, but they are not useful.

Is there a workflow that will work here?

**Comment by jdbann** [comment]
@ioev I had this too, but digging around other `esbuild` issues led me to this fix which worked for me: https://github.com/rails/jsbundling-rails/issues/40#issuecomment-1006503192

**Comment by dhh** [comment]
For others, you must set `config.assets.debug = false`.

**Comment by ioev** [comment]
This fix in conjunction with:
/assets/application.js-5ffbeb1e467c0b9cbdb8a73cf302d6957be3216a46ac4392bdc648ca3d1d8d57.map

allows the sourcemaps to be located, but they still don't seem to actually work in the browser.

**Comment by dhh** [comment]
You need to using sprockets-rails 3.4.2+ for this to work.
