### ISSUE TITLE
Stimulus does not connect for default new rails apps with --javascript=webpacker

### ISSUE THREAD

**Issue by jasonfb** [rails/jsbundling-rails#74]
Hey can someone tell me if this new jsbundling-rails using Webpack paradigm can work with Stimlus? 

Something seems very strange I've been back and forward over **rails new** lately and the flags produce some very strange results results in an impact to Stimulus being incorrectly setup when you use the `--css=bootstrap` flag or the `--javascript=webpack` flag.

Steps to reproduce: 
1. `rails new TestJSBundlingRails20220122 --javascript=webpack`
2. `rails generate controller Articles` 
3. add `def index` to articles controller, uncomment line `root "articles#index"` in routes file, them create `views/articles/index.erb` with this contents:

```
<div data-controller="hello">
  hello world
</div>
```

in the app/javascript/controllers/hello_controller.js add a console message:

```
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  connect() {
    
    console.log("hello controller was connected")
    this.element.textContent = "Hello World!"
  }
}
```

Now load the browser.

Actual Result: You will see only "Hello world" but nothing logged in the console

<img width="817" alt="DevTools - 127 0 0 1:3000: 2022-01-22 15-41-09" src="https://user-images.githubusercontent.com/59002/150654730-1d07981b-bf06-4bed-93d6-57e055bf255d.png">

Expected Result: The hello controller is connected to the page correctly and the console log message show up

Sample reproduction here:

https://github.com/jasonfb/TestJSBundlingRails20220122

**Comment by jasonfb** [comment]
as this point, the only way I can get stimulus working on new Rails 7 apps is to use neither `--css=bootstrap` nor `--javascript=webpack` 

when I  use either of these, I get some kind of a "registry" file at **app/javascript/controllers/applicationl.js** (see below)

please note that this file is inconsistent with what is generated by the default **rails new**, which uses a dynamic loader that makes the registering of each Stimulus class name (and thus rebuilding of this file) unnecessary. 

However, when I copy the dynamic loader content into an app generated in this registry-style pattern, it doesn't seem to work. (That is, I can't seem to swap out the dynamic loader content for the registry content.)

TO be clear, under these circumstances, I can't get get any Stimulus controllers to load at all, with or without  the dynamic loader. It is only with the default rails new that I can get the stimulus controllers to load. 

here is the registry loader that comes with `--css=bootstrap` or `--javascript=webpack` 

```
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)
```

**Comment by dhh** [comment]
I can't replicate this on Rails 7.0.1. When you start with --javascript=webpack you get the static index loader by design. The dynamic loader is only intended to be used with import maps.

Steps to get things working:
1. rails new testapp --javascript=webpack
2. rails generate scaffold post title:string
3. Add `<div data-controller="hello"></div>` to app/views/posts/index.html.erb
4. See "Hello World" from Stimulus on localhost:3000/posts

**Comment by jasonfb** [comment]
I tested this against Ruby 2.7. I will check it against Ruby 3.0 now and report back here.

**Comment by jasonfb** [comment]
ok @dhh -- I have now recreated this issue using a 2nd laptop that did not previously have Rails 7.0.1 on it. same result. **Would you please consider that your machine may have yanked cached gems causing your new rails build to work for only you but not for everyone else?**

Please re-open the issue or supply the rails build for us to examine the `Gemfile.lock`. this does not make sense.

**Comment by jasonfb** [comment]
here is the Gemfile.lock that I am getting. I can't see anything wrong with it by examination, but if possibly your machine has yanked cached gems you will be building against gems that make your apps work. 

https://gist.github.com/jasonfb/fa99be3bed6eec5a394b0205a53c9f56

**Comment by jasonfb** [comment]
@dhh -- nevermind! 

the problem here is that this is what happens when you don't actually install webpack as a node module using `npx webpack`

**Comment by jasonfb** [comment]
RESOLITION & NOTICE:

The problem here is that I was running my Rails server with `rails s`, which won't install webpack as a node module. Without webpacker, there's no 

You are now encouraged to use the new development command, which takes care of both (although requires a reload of the web browser to kick in webpack:

bin/dev rails

If using rails server (`rails s`), you must run `npx webpack` first or else your webpack won't be installed. 

Remember, this affects only apps built using the new `--css` and `--javascript` flags. 

there are likely no yanked cached gems on DHH's machine I just didn't know what else to think of next!

**Comment by jasonfb** [comment]
https://jasonfleetwoodboldt.com/courses/stepping-up-rails/rails-7-new-app-with-js-bundling-css-bundling/
