### ISSUE TITLE
Can't load images in JavaScript files

### ISSUE THREAD

**Issue by cirdes** [rails/jsbundling-rails#76]
Hi,

I'm trying to migrate my Rails + React application from Webpacker to Jsbundling + Esbuild following [switch_from_webpacker](https://github.com/rails/jsbundling-rails/blob/main/docs/switch_from_webpacker.md) guide to first replace webpacker for Jsbundling

Everything is bundled to "app/assets/builds" by webpack, [images included](https://github.com/rails/jsbundling-rails/blob/main/docs/switch_from_webpacker.md#optional-fonts-images-svg). 

application.js and application.css are working fine in application.html.erb but the images in jsx files aren't loading.

My React component are trying to load "0bdd8103a525a17c3528e4f40d701b33.svg" the same as output in assets/builds folder but public/assets has the digested version of my svg "0bdd8103a525a17c3528e4f40d701b33-b8fb0ca2943e7724f64b3717f8a3e2b3ecb321adac1053107f2c89142efffd17.svg"

```
import React from "react";
import Logo from "Assets/logo-brand.svg";

export default function Img() {
  return <img height="46px" src={Logo}  />;
}
```

I'm not sure if the correct approach is to move all assets from assets/build to public/asssets with a rake or if it is possible to skip sprockets-rails digest for images and rely on webpack digested file or if there is another way to load imagens inside js files

Thanks for jsbundling effort!

**Comment by richardkmiller** [comment]
@cirdes PR #58 should be helpful to you. The short answer is to open `package.json` under `"scripts"` and edit the `esbuild` script to include `--public-path=/assets`. In the PR I suggested `--public-path=assets` but after further use, I found an issue that was resolved by using the leading slash: `--public-path=/assets`. Let me know if that doesn't work for you.

**Comment by richardkmiller** [comment]
@cirdes Realizing too, you probably need step 2 from the PR, which is, in your case, to add `--loader:.svg=file` to your esbuild script. That should cause esbuild to copy `logo-brand.svg` to your build folder.

**Comment by cirdes** [comment]
@richardkmiller , I'm planing to move for esbuild but as first step I just replace webpacker for jsbundling.
In my scripts I have `webpack --config ./webpack.config.js`

webpack.config.js
```
const path = require("path");

module.exports = {
  mode: "production",
  devtool: "source-map",
  entry: {
    application: "./app/javascript/application.js",
  },
  resolve: {
    extensions: [".css", ".yml", ".js", ".jsx"],
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ["babel-loader"],
      },
      {
        test: /\.(png|jpe?g|gif|svg)$/i,
        use: [
          {
            loader: "file-loader",
          },
        ],
      },
    ],
  },
  output: {
    filename: "[name].js",
    sourceMapFilename: "[name].js.map",
    path: path.resolve(__dirname, "app/assets/builds"),
  },
};
```

Webpack moves everything to "app/assets/builds" as expected but `sprockets` moves my js, css and .svg files to public/assets and apply the digest. Because of the digested version in public/assets my JS components can't find images.

**Comment by cirdes** [comment]
@richardkmiller , my components are trying to load "assets/9ec374fef9afac22b97095d845b3db6a.png"(file generated by webpack at app/assets/build) instead of "assets/9ec374fef9afac22b97095d845b3db6a-b8fb0ca2943e7724f64b3717f8a3e2b3ecb321adac1053107f2c89142efffd17.svg" file that appears in public/assets

**Comment by richardkmiller** [comment]
Ah I see what you mean. I'm not sure about this, but you may be able to make it work by removing the keyword `hash` from your webpack configuration so webpack won't rename the svg file. Then you can use the asset pipeline helpers to refer to it by name in your JavaScript. Even though the asset pipeline will add a hash/digest, that's ok because the helpers still work. 

These might help:

https://stackoverflow.com/questions/45809887/webpack-disable-hashing-of-image-name-on-output

https://guides.rubyonrails.org/asset_pipeline.html#javascript-coffeescript-and-erb (section 2.3.3)

**Comment by ioev** [comment]
Same general problem, but with rails 7.0 + propshaft + jsbundling + esbuild, specifically with leaflet-react.  Using ```--loader:.png=file --public-path=/assets``` and am trying to override the paths as mentioned in https://github.com/PaulLeCam/react-leaflet/issues/453#issuecomment-731732137 and the file ends up as ```assets/builds/marker-icon-2V3QKKVC.png```, but rails can't find this file without it's own digest.  I've also tried using ```--entry-names=[name]-[hash].digested``` on esbuild, but this doesn't appear to apply to the file loader.

**Comment by giedomak** [comment]
> Propshaft looks for the specific pattern of `-[digest].digested.js` as the postfix to any asset file as an indication that the file has already been digested.

See: https://github.com/rails/propshaft#bypassing-the-digest-step

Looks like there is bug in the above 'bypassing the digest step' feature for both propshaft and sprockets.

This is the issue for sprockets:
- https://github.com/rails/sprockets/issues/728

This will fix it for sprockets:
- https://github.com/rails/sprockets/pull/726

It has already been fixed for propshaft:
- https://github.com/rails/propshaft/pull/55

**Comment by cirdes** [comment]
@giedomak , thanks for pointing out this PRs. Hope https://github.com/rails/sprockets/pull/726 could be merged soon.

**Comment by cirdes** [comment]
@jon-sully , It's working with JSB-Rails + Webpack 5!

I'm using webpack with this config and now sprockets are not re-stamping the assets.


```
 {
        test: /\.(png|jpe?g|gif|svg)$/i,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "[name]-[hash].digested.[ext]",
            },
          },
        ],
      },
```

**Comment by jon-sully** [comment]
Nice 👍 yeah same premise. Good stuff! 🤓

**Comment by richardkmiller** [comment]
@cirdes If it were my decision, I guess I might leave this as a post-install configuration step. For example, the README explains how to use `--loader:.png=file` but you have to add it manually. Likewise, the use of `--public-path` could be explained in the README for those who need it. If you agree, I'll create a PR for it, and I'll also add the leading slash as the default which I did not include in #58.

**Comment by andrewhavens** [comment]
I'm having a similar, but maybe slightly different problem. After upgrading from Rails 6 and switching from Webpack to esbuild, I can load images in development, but not after deploying to production (Heroku). In production, it looks like an additional fingerprint is added to the asset path.

```
remote:        $ node esbuild.config.js
remote:        Done in 2.79s.
remote:        I, [2022-06-15T20:31:18.764370 #688]  INFO -- : Writing /tmp/build_ec2e3794/public/assets/logo-Y5WNYHYB.digested-6f90874fa6e725ac79c88da3fc17b3dd7739c0a66c44586d8d247951fe8c06d6.png
```

My esbuild.config.js looks like this:

```js
const path = require("path")
const vuePlugin = require("esbuild-vue")

require("esbuild").build({
  entryPoints: ["application.js", "compartment.js"],
  bundle: true,
  loader: {".png": "file"},
  outdir: path.join(process.cwd(), "app/assets/builds"),
  absWorkingDir: path.join(process.cwd(), "app/javascript"),
  publicPath: "/assets",
  assetNames: "[name]-[hash].digested",
  watch: process.argv.includes("--watch"),
  plugins: [vuePlugin()],
}).catch(() => process.exit(1))
```

**Comment by brenogazzola** [comment]
@andrewhavens Are you on Sprockets? The digest skip feature os only available on master. There are no released versions with it yet.

**Comment by gsouf** [comment]
Also had a bunch of issue in rails 6 + sprocket + webpack with external files and code splitting due to the re-stamping . So we decided to bypass all the asset management of rails and relying only on webpack by outputting webpack directly to `public`: 

```js
output: {
        ....
        path: 'public/js'
    },
```

and stamping by ourselves the application.js. That might not be the rail's flavor, it gives us the control and flexibility we needed on webpack and it works very well for us and saves us a lot of headaches until a better solution arises

**Comment by tgaff** [comment]
> Edit: Digging a little deeper into the esbuild config, I got this to work by using the `asset-names` parameter: `--loader:.png=file --public-path=/assets --asset-names=[name]-[hash].digested`

Confirming that @ioev 's suggestion of `--asset-names=[name]-[hash].digested` works in production for a Sprockets + jsbundling + esbuild install.

**Comment by shepmaster** [comment]
A note for people hitting the same problem as me: Your asset name *must* have a dash before the digest.

The default value for `file-loader`'s `name` option is `[contenthash].[ext]`, so I changed it to `[contenthash].digested.[ext]`. However, sprockets [uses a regex that looks for the hyphen](https://github.com/rails/sprockets/blob/v4.2.0/lib/sprockets/digest_utils.rb#L185C2-L187).

After changing the option to `[name]-[contenthash].digested.[ext]` or `asset-[contenthash].digested.[ext]`, the extra digest is no longer appended.
