### ISSUE TITLE
When generating rails 7 new with js, the file at app/javascript/controllers/index.js is different

### ISSUE THREAD

**Issue by jasonfb** [rails/jsbundling-rails#77]
When generating a Rails app with `rails new`, the file at **app/javascript/controllers/index.js**, whose job is to load all the controllers is:

```
import { application } from "controllers/application"

// Eager load all controllers defined in the import map under controllers/**/*_controller
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)
```

When generating a new rails app using `--javascript=webpack` or `--css=bootstrap`, I noticed that the file at **app/javascript/controllers/index.js** looks like this instead:

```
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
```

Is one of these preferred over the other? 

is the choice between the implementations relevant to the usage of the flag or is it just haphazard? (that is, is there some reason why it is like this)

my 2¢: It seems that smart/eager loading that eliminates the need to update the manifest file is better than having to remember to update a manifest file
-Jason

**Comment by dhh** [comment]
Different loaders depending on whether the app is using import maps or a js bundler. Eager loading is not compatible with a js bundler, and therefore uses the manifest.
