### ISSUE TITLE
Question about Comparison document

### ISSUE THREAD

**Issue by hachi8833** [rails/jsbundling-rails#78]
In [comparison_with_webpacker.md](https://github.com/rails/jsbundling-rails/commit/1d027b7890f200f5371640c43be8b7838fb167c6#diff-66e50b057deb14910b371f5e428cfd71858368529440cd7e4acd908bb9af51fa):

> - `jsbundling-rails` is a lighter integration. `webpacker` _can be_ more involved and opinionated. The difference is whether or not you use only the view helpers of `shakapacker` or include the webpack configuration setup.

What does the second sentence compare between?

**Comment by justin808** [comment]
@hachi8833 have I addressed your question with the updates in #79?

**Comment by hachi8833** [comment]
@justin808 Thank you for the updates! Its' OK for me.

**Comment by justin808** [comment]
@rafaelfranca there are a bunch of good doc updates waiting for merge.
