### ISSUE TITLE
Heroku not building js, rare behavior

### ISSUE THREAD

**Issue by michelson** [rails/jsbundling-rails#82]
Hello there, I've been days banging my head on this, and I could not explain what's happening:

I'm using _jsbundling_ on a Rails 6.1.4.4 / sprockets (4.0.2), the compilation works on local, ( files are stored in app/assets/build and served properly by sprockets). I can see the app running ok, but when I deploy to Heroku the `rails assets:precompile` I get different results., 

In Heroku, the asset files are not copied to the public/assets. It seems that it find files on public/assets, so it skips that part.
I've done an "enhance" to the `assets:precompile` rake task in order to remove all the files in the public/assets before the precompilation. That way, it generates the files in Heroku, but the JS files are not copied into public/assets 🤯. It copies only a portion of the assets, like images and CSS but not the .js file. I've replicated that in a [github action build](https://github.com/chaskiq/chaskiq/runs/5089516537?check_suite_focus=true#step:7:287) where the config.assets is `config.assets.compile = false` so it kinda replicates what's happening in production.

I've tried many strategies to get this working but without avail. Has anyone seen this rare behavior before?

**Comment by michelson** [comment]
also running the ` RAILS_ENV=test rails assets:precompile` in local gives me different result, it does compile the files and copies the JS to public/assets, I'm clueless :(

**Comment by marckohlbrugge** [comment]
Did you solve this? I'm running into the same problem on Render

**Comment by marckohlbrugge** [comment]
I solved it by making sure there was an `app/assets/builds` directory. Also see https://github.com/rails/jsbundling-rails/issues/60

**Comment by michelson** [comment]
I will close this as the specific issue was solved.
