### ISSUE TITLE
jsbundling files overwriting cssbundling generated files.

### ISSUE THREAD

**Issue by Ashvith** [rails/jsbundling-rails#91]
While generating files for jsbundling and cssbundling, some of the files are overwritten. Not sure if that will cause my app to behave abnormally in the future, so I would like to know beforehand how it impacts my app, because I am suspecting that this is probably breaking my Bootstrap JS.

I've tried `rails assets:precompile`, as well as running the app from `bin/dev`, but it just won't work.

Some of the errors/warnings I've received:
```sh
File unchanged! The supplied flag value not found!  app/assets/config/manifest.js
```

```sh
File unchanged! The supplied flag value not found!  .gitignore
```

```sh
File unchanged! The supplied flag value not found!  .gitignore
```

```sh
conflict  bin/dev
Overwrite /home/ashvith/Desktop/todo-app/bin/dev? (enter "h" for help) [Ynaqdhm] Y
    force  bin/dev
```

I've started my app with the default settings (importmap, hotwire, sqlite3). Removed the importmap-rails, and replaced them with jsbundling-rails and cssbundling-rails.

**Comment by yahonda** [comment]
I think this issue has been resolved by using cssbundling-rails 1.1.0 and jsbundling-rails 1.0.2 via https://github.com/rails/jsbundling-rails/pull/95
