### ISSUE TITLE
Set Webpack `mode` from what?

### ISSUE THREAD

**Issue by jon-sully** [rails/jsbundling-rails#98]
Hey team,

Before submitted a dead-simple PR I just wanted to raise an issue and ask if a typo was made in the [Switch from Webpacker 5 to jsbundling-rails with webpack](https://github.com/rails/jsbundling-rails/blob/main/docs/switch_from_webpacker.md#switch-from-webpacker-5-to-jsbundling-rails-with-webpack) guide. My own team recently realized that our `jsbundling-rails` + `webpack` setup was generating development builds in production — the reason ultimately being that we previously used `webpacker` (which I presume forced `webpack` into `production` mode because the _`RAILS_ENV`_ was in production mode) and once we moved forward to `jsbundling-rails` + `webpack` (Rails 7) setup, we never actually added `RAILS_ENV` to our production environment (Heroku). That said, there's a bit at the end of that guide that goes:

> ## Optional: Add support for development environment
> 
> `jsbundling-rails` ships with only `production` mode. You can dramatically speed up build times during development by switching to `mode: 'development'`.
> 
> ```diff
> // Make the following changes in webpack.config.js
> + const mode = process.env.NODE_ENV === 'development' ? 'development' : 'production';
> 
> module.exports = {
> -  mode: "production",
> +  mode,
> -  devtool: "source-map",
>   …
> +  optimization: {
> +    moduleIds: 'hashed',
> +  }
> }
> ```

Which we _did_ do, but since there was no `NODE_ENV` in our production environment to begin with, didn't do much. Thinking about it a little bit, was this line a typo? 

> const mode = process.env.NODE_ENV === 'development' ? 'development' : 'production';

Was that supposed to actually pull the current environment from the _`RAILS_ENV`_? I feel like the line as written isn't that useful — Webpack _already_ listens to `NODE_ENV` and sets the mode by default based on that value (see the "Tip" on https://webpack.js.org/configuration/mode/). If it was supposed to be `RAILS_ENV` then that makes more sense — I wouldn't have to set a `NODE_ENV` on my production (or local) hosts and webpack would always just follow the Rails environment (which feels nice). 

Just wanted to ask 🙂

**Comment by jon-sully** [comment]
FWIW I've set my Webpack config as 

```js
const mode = process.env.RAILS_ENV

module.exports = {
  mode,
  ...
  // etc
```

**Comment by Faq** [comment]
That introduced with https://github.com/rails/jsbundling-rails/commit/922b030083bf5fa100badae6b1e3a1e37321c9fc by @bholtbholt

**Comment by bholtbholt** [comment]
@jon-sully its possible it could/should be RAILS_ENV. In the app I did the conversion on we had NODE_ENV set so it was changing between builds.

It's been about over a year since I did the conversion and wrote the guide, so it's also possible Heroku, Rails, and Webpack changes have affected it. If it's out of date then it's definitely worth updating.

The important piece to keep in mind is that with `mode: "development"` webpack compiles and watches in a different way, using local caches, which makes the build faster.

**Comment by jon-sully** [comment]
I opened this over a year ago and we don't even use Webpack anymore so 😆 no biggie from me!

**Comment by bholtbholt** [comment]
I wonder why i got tagged today 🤷‍♂️

**Comment by jon-sully** [comment]
@Faq commented 8 hours ago but prior comment was a year ago 😅 Alas.

**Comment by Faq** [comment]
Thank you for the answer.

**Comment by dhh** [comment]
Feel free to update docs in a PR if anything is still out of date.
